### ISSUE TITLE
Link Component

### ISSUE THREAD

**Issue by danhenderson** [everydayhero/constructicon#46]
There has been a bit of conjecture around how we create links in our static sites, and avoid fetching from prismic at runtime.

Would it be worth defining our own Link component, that abstracts this decision and handles adding target=_self, or whatever our chosen method is.

We could also make it handle on page # links as well, all in one place.

I have found myself writing similar components to handle this in a few projects

**Comment by rowanhogan** [comment]
Could not agree more, see [here](https://github.com/everydayhero/40-hour-famine/blob/master/source/components/Link/index.js) for an example where I wanted to set `target='_blank'` for external links, and `_self` for relative links.

**Comment by rowanhogan** [comment]
I had a quick look at this, though it involves making React Router a dependency of Constructicon, which doesn't feel right (and it's also difficult to test). So for now I'll leave it.
